Not using this .... Some issues

In [28]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [29]:
matrix = np.array([
    [-1, -1, -1, -1],
    [0, 0, 0, 0],
    [1, 1, 1, 1],
    [0, 0, 1, 1],
    [1, 1, -1, -1],
    [-1, -1, 0, 0],
    [-1, 1, 0, 1],
    [0, -1, 1, -1],
    [1, 0, -1, 0],
    [1, 0, 0, -1],
    [-1, 1, 1, 0],
    [0, -1, -1, 1],
    [1, -1, 1, 0],
    [-1, 0, -1, 1],
    [0, 1, 0, -1],
    [0, 1, -1, 0],
    [1, -1, 0, 1],
    [-1, 0, 1, -1]
])

matrix.shape

(18, 4)

In [30]:
df = pd.read_csv(r'../Data/CleanedData.csv')
df.head()

helical_angle  helical_layer_count  hoop_layer_count  bust_pressure  \
0             14                    3               3.0            519   
1             14                    3               3.0            383   
2             14                    3               6.0            438   
3             14                    3               9.0            552   
4             14                    6               6.0            700   

   tensile_str  e1_gpa  youngs_modulus  poision_ratio  yeild_strength  \
0       1082.0   108.3            57.5           0.33           240.3   
1       1082.0   108.3            57.5           0.33           240.3   
2       1082.0   108.3            57.5           0.33           240.3   
3       1082.0   108.3            57.5           0.33           240.3   
4       1082.0   108.3            57.5           0.33           240.3   

   ult_tensile_strength  liner_thickness  diameter  doily_layers  
0                   317                6       130             0  
1                   317                6       130             0  
2                   317                6       130             0  
3                   317                6       130             0  
4                   317                6       130             0

In [31]:
x = df.drop(columns=['bust_pressure']).to_numpy()
y = df['bust_pressure'].to_numpy()
x.shape, y.shape

((43, 12), (43,))

Applying PCA

In [32]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [33]:
pca = PCA(n_components=4)  
x_pca = pca.fit_transform(x_scaled)

In [34]:
x_pca.shape

(43, 4)

In [35]:
x_pca

array([[ 7.46929077e-01, -2.49600850e+00, -4.37445677e-01,
         1.63390310e-01],
       [ 7.46929077e-01, -2.49600850e+00, -4.37445677e-01,
         1.63390310e-01],
       [ 9.95674142e-01, -1.69952058e+00, -7.20208788e-01,
        -6.80746502e-01],
       [ 1.24441921e+00, -9.03032656e-01, -1.00297190e+00,
        -1.52488331e+00],
       [ 1.18845386e+00, -1.06371865e+00, -7.24855486e-01,
        -3.16970413e-02],
       [ 1.18845386e+00, -1.06371865e+00, -7.24855486e-01,
        -3.16970413e-02],
       [ 8.75448891e-01, -2.07214055e+00, -4.40543476e-01,
         5.96089951e-01],
       [ 1.77715358e+00,  8.46001149e-01, -1.10806856e+00,
        -2.91813510e-01],
       [ 1.92432851e+00,  1.32343110e+00, -1.20387183e+00,
        -3.56842627e-01],
       [ 1.62997865e+00,  3.68571199e-01, -1.01226529e+00,
        -2.26784393e-01],
       [ 1.96993330e+00,  1.48180308e+00, -1.11271526e+00,
         3.57235951e-01],
       [ 1.38123358e+00, -4.27916725e-01, -7.29502184e-01,
      

In [36]:
# z_min = x_pca.min(axis=0)
# z_max = x_pca.max(axis=0)
# z_code = 2*(x_pca - z_min) / (z_max - z_min) - 1

Getting the polynomial features

In [37]:
poly = PolynomialFeatures(degree=2, include_bias=True)
x_poly = poly.fit_transform(x_pca)
x_poly.shape

(43, 15)

In [38]:
x_poly[0]

array([ 1.        ,  0.74692908, -2.4960085 , -0.43744568,  0.16339031,
        0.55790305, -1.86434133, -0.3267409 ,  0.12204097,  6.23005845,
        1.09186813, -0.4078236 ,  0.19135872, -0.07147438,  0.02669639])

In [39]:
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=False)

model.fit(x_poly, y)

LinearRegression(fit_intercept=False)

In [40]:
print(model.coef_)
print(model.intercept_)

[ 2840.53634493  -648.67754853  -544.09385959  -130.36160407
  3907.50219567  -156.36695131  -576.37726017   536.98165429
 -4033.35591143  -215.20430215 -2389.33420648  1096.45224521
  -146.87037217 -2045.59093993   237.11701437]
0.0


In [41]:
feature_names = poly.get_feature_names_out([f'z{i+1}' for i in range(4)])
betas = dict(zip(feature_names, model.coef_))
betas

{'1': np.float64(2840.5363449312304),
 'z1': np.float64(-648.6775485343625),
 'z2': np.float64(-544.0938595892175),
 'z3': np.float64(-130.3616040675217),
 'z4': np.float64(3907.5021956687788),
 'z1^2': np.float64(-156.36695131184956),
 'z1 z2': np.float64(-576.377260173567),
 'z1 z3': np.float64(536.9816542878006),
 'z1 z4': np.float64(-4033.3559114303885),
 'z2^2': np.float64(-215.20430215082024),
 'z2 z3': np.float64(-2389.3342064790886),
 'z2 z4': np.float64(1096.4522452102935),
 'z3^2': np.float64(-146.87037216966135),
 'z3 z4': np.float64(-2045.5909399340883),
 'z4^2': np.float64(237.11701437347676)}

In [42]:
y_pred = model.predict(x_poly)

In [43]:
model.score(x_poly, y)

0.8882485176482994

In [44]:
y_pred = model.predict(x_poly)
epsilon = np.mean(y_pred - y)
epsilon

np.float64(-1.2386577551762118e-11)

In [45]:
np.dot((y - y_pred).T, (y - y_pred))

np.float64(414856.9978789534)

In [46]:
beta = np.dot(np.dot(np.linalg.inv(np.dot(x_poly.T, x_poly)), x_poly.T), y)
beta

array([ 2056.29231404,  -266.29329643,  -774.78680549,  -980.66472992,
        4024.32850428,   -77.51747501,  -532.43725512,  1009.42091611,
       -4083.43076348,  -232.42117067, -2537.893672  ,  1115.76025303,
        -176.51191789, -2032.34754743,   235.8646835 ])

Interpolating

In [47]:
# n = 25
# a = x[n]
a = np.array([
    [400.0, 5.0, 200.0, 0.3, 350.0, 50.0, 500.0, 30.0, 10, 10, 2.0, 5],
    [450.0, 5.5, 210.0, 0.29, 360.0, 55.0, 520.0, 35.0, 12,  9, 1.8, 4]
])
a = scaler.transform(a)
a = pca.transform(a)
a = poly.transform(a)
a = model.predict(a)
# a, y[n]
a

array([-1.58442074e+10, -1.71620327e+10])

In [48]:
a = np.array([
    [400.0, 5.0, 200.0, 0.3, 350.0, 50.0, 500.0, 30.0, 10, 10, 2.0, 5],
    [450.0, 5.5, 210.0, 0.29, 360.0, 55.0, 520.0, 35.0, 12,  9, 1.8, 4]
])
a = scaler.transform(a)
a = pca.transform(a)
a = poly.transform(a)
sum(np.dot(beta.reshape(1,-1), a.T))

array([-1.27512852e+10, -1.38104381e+10])

Synthetic Data Generation

In [49]:
HELICAL_ANGLE_LB = 10
HELICAL_ANGLE_UB = 30

HELICAL_LAYER_LB = 3
HELICAL_LAYER_UB = 15

HOOP_LAYER_LB = 1
HOOP_LAYER_UB = 15

TENSILE_STRENGTH_LB = 600
TENSILE_STRENGTH_UB = 1100

E1_LB = 95
E1_UB = 110

YOUNGS_MODULUS_LB = 55
YOUNGS_MODULUS_UB = 150

POISSONS_RATIO_LB = 0.25
POISSONS_RATIO_UB = 0.35

YEILD_STRENGTH_LB = 230
YEILD_STRENGTH_UB = 250

ULT_STRENGTH_LB = 310
ULT_STRENGTH_UB = 370

LINER_THICKNESS_LB = 0.4
LINER_THICKNESS_UB = 0.6

DIAMETER_LB = 120
DIAMETER_UB = 150

DOLIY_LB = 7
DOLIY_UB = 25


In [50]:
feature_ranges = {
    'helical_angle': (HELICAL_ANGLE_LB, HELICAL_ANGLE_UB),         # degrees
    'helical_layer_count': (HELICAL_LAYER_LB, HELICAL_LAYER_UB),        # integer
    'hoop_layer_count': (HOOP_LAYER_LB, HOOP_LAYER_UB),           # integer
    'tensile_str': (TENSILE_STRENGTH_LB, TENSILE_STRENGTH_UB),         # MPa
    'e1_gpa': (E1_LB, E1_UB),                  # GPa
    'youngs_modulus': (YOUNGS_MODULUS_LB, YOUNGS_MODULUS_UB),      # GPa
    'poision_ratio': (POISSONS_RATIO_LB, POISSONS_RATIO_UB),         # unitless
    'yeild_strength': (YEILD_STRENGTH_LB, YEILD_STRENGTH_UB),      # MPa
    'ult_tensile_strength': (ULT_STRENGTH_LB, ULT_STRENGTH_UB),# MPa
    'liner_thickness': (LINER_THICKNESS_LB, LINER_THICKNESS_UB),         # mm
    'diameter': (DIAMETER_LB, DIAMETER_UB),              # mm
    'doily_layers': (DOLIY_LB, DOLIY_UB)                 # integer
}

features = list(feature_ranges.keys())
features

['helical_angle',
 'helical_layer_count',
 'hoop_layer_count',
 'tensile_str',
 'e1_gpa',
 'youngs_modulus',
 'poision_ratio',
 'yeild_strength',
 'ult_tensile_strength',
 'liner_thickness',
 'diameter',
 'doily_layers']

In [51]:
# Generate N samples
N = 300  # You can change this
synthetic_samples = []

np.random.seed(123)  # For reproducibility

for _ in range(N):
    sample = []
    for feat in features:
        low, high = feature_ranges[feat]
        if isinstance(low, int) and isinstance(high, int):
            sample.append(np.random.randint(low, high+1))
        else:
            sample.append(np.random.uniform(low, high))
    synthetic_samples.append(sample)

X_synth = np.array(synthetic_samples)


In [52]:
y_synth = model.predict(poly.transform(pca.transform(scaler.transform(X_synth))))
y_synth.shape

(300,)

In [53]:
df_synth = pd.DataFrame(X_synth, columns=features)
df_synth['bust_pressure'] = y_synth
df_synth = df_synth.round(2)
df_synth.to_csv('../Data/InterpolatedData.csv', index=False)

df_synth.shape

(300, 13)

In [54]:
df_synth.head(10)

helical_angle  helical_layer_count  hoop_layer_count  tensile_str  e1_gpa  \
0           23.0                  5.0              13.0        698.0   101.0   
1           10.0                  3.0              10.0        939.0   109.0   
2           12.0                  7.0               9.0       1045.0    95.0   
3           11.0                 15.0               9.0        987.0   105.0   
4           14.0                 14.0              12.0        853.0   107.0   
5           30.0                 10.0              12.0       1038.0   102.0   
6           22.0                  5.0               2.0        601.0    98.0   
7           13.0                 14.0               6.0       1073.0   102.0   
8           16.0                  6.0              10.0        798.0   107.0   
9           11.0                  3.0               6.0        960.0   108.0   

   youngs_modulus  poision_ratio  yeild_strength  ult_tensile_strength  \
0            72.0           0.32           231.0                 342.0   
1            91.0           0.29           234.0                 359.0   
2            62.0           0.32           250.0                 348.0   
3           124.0           0.29           232.0                 368.0   
4            85.0           0.30           243.0                 361.0   
5            56.0           0.30           235.0                 365.0   
6            99.0           0.29           246.0                 366.0   
7            58.0           0.33           249.0                 366.0   
8           109.0           0.31           247.0                 356.0   
9           141.0           0.28           238.0                 335.0   

   liner_thickness  diameter  doily_layers  bust_pressure  
0             0.52     135.0          16.0      -42162.46  
1             0.44     122.0          14.0      -17232.48  
2             0.46     142.0           9.0      -26439.96  
3             0.50     133.0          25.0       -6659.12  
4             0.51     126.0          21.0       -9581.28  
5             0.50     140.0          24.0      -25826.14  
6             0.47     142.0          10.0        7152.35  
7             0.51     129.0          21.0       -1165.77  
8             0.43     140.0          10.0      -38472.73  
9             0.46     120.0          10.0        1674.76